<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('songs', function (Blueprint $table) {
            $table->id();

            $table->string('title');
            $table->string('artist');
            $table->string('musical_key', 20)->nullable();

            $table->string('youtube_url', 500)->nullable();
            $table->string('source_url', 500)->nullable();

            $table->json('video_lesson')->nullable(); // list of video lessons: [{instrument, title, link}]
            $table->json('structure'); // generated by the Música project

            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent()->useCurrentOnUpdate();

            $table->index('artist', 'idx_artist');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('songs');
    }
};
