name: Build and Deploy

on:
  push:
    branches:
      - master  # Ajuste conforme necessário

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Zip
        run: zip -r build.zip public/build
      # - name: Copy to server
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.IP }}
      #     username: ${{ secrets.USER }}
      #     password: ${{ secrets.PASSWORD }}
      #     source: "build.zip"
      #     target: "~/public_html/admin"
      # - name: Multiple Command on server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.IP }}
      #     username: ${{ secrets.USER }}
      #     password: ${{ secrets.PASSWORD }}
      #     script: |
      #       cd ~/public_html/admin
      #       git pull origin master
      #       unzip -o build.zip
      #       rm build.zip
